version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/httpd.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/files.sh
      timeout: 300
      runas: root
    - location: scripts/restart.sh
      timeout: 300
      runas: root
